# Generated by Django 5.0.2 on 2024-02-10 08:03

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('default', 'select Field'), ('homepage', 'Homepage'), ('about_us', 'About Us'), ('menu', 'Our Menu'), ('franchise', 'Franchise'), ('contact_us', 'Contact Us'), ('book_order', 'Book an Order')], default='default', max_length=50)),
                ('desk_image', models.ImageField(default='', upload_to='images/sub-banner/desktop/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('mob_image', models.ImageField(default='', upload_to='images/sub-banner/mobile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alt_text', models.CharField(default='Banner', max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
            ],
        ),
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/cat_image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('email', models.EmailField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid Email ID.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('subject', models.CharField(default='', max_length=300)),
                ('message', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('email', models.EmailField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid Email ID.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('phone', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid Phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(default='', max_length=300)),
                ('address2', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='user_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('image', models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('client_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
