# Generated by Django 5.0.2 on 2024-02-11 15:01

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('pro_keyword', models.CharField(blank=True, max_length=255)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('recipe', models.BooleanField(default=False)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_in_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/product/')),
                ('images', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jopaji.category_master')),
            ],
        ),
    ]
