# Generated by Django 5.0.2 on 2024-02-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0004_remove_tbl_product_discount_remove_tbl_product_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='flavour',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='pro_keyword',
        ),
    ]
