# Generated by Django 5.0.2 on 2024-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0005_remove_tbl_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
