# Generated by Django 5.0.2 on 2024-02-11 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0006_tbl_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_master',
            name='desk_image',
            field=models.ImageField(blank=True, upload_to='images/cat_image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='category_master',
            name='mob_image',
            field=models.ImageField(blank=True, upload_to='images/cat_image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
