# Generated by Django 5.0.2 on 2024-02-12 02:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0007_category_master_desk_image_category_master_mob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_master',
            name='cat_descr',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
