# Generated by Django 5.0.2 on 2024-02-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0008_category_master_cat_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_master',
            name='slug',
        ),
    ]
