# Generated by Django 5.0.2 on 2024-02-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0009_remove_category_master_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_master',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
