# Generated by Django 5.0.2 on 2024-02-12 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jopaji', '0010_category_master_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('phone', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid Phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=64, validators=[django.core.validators.RegexValidator(message='Please enter a valid Email ID.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('h_no', models.IntegerField(blank=True, max_length=3)),
                ('city_or_village', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(max_length=6)),
                ('address', models.CharField(default='', max_length=300)),
                ('state', models.CharField(choices=[('default', 'select Field'), ('homepage', 'Homepage'), ('about_us', 'About Us'), ('menu', 'Our Menu'), ('franchise', 'Franchise'), ('contact_us', 'Contact Us'), ('book_order', 'Book an Order')], default='default', max_length=50)),
                ('admin_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
